from __future__ import annotations

import re
import smtplib
from datetime import datetime, timezone
from email.message import EmailMessage
from io import BytesIO
from typing import Any, Dict, List

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from .config import get_settings


MAX_EMAIL_CANDIDATES = 10
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


class EmailServiceError(RuntimeError):
    pass


def is_valid_email(email: str) -> bool:
    return bool(EMAIL_REGEX.match(email.strip()))


def _require_smtp_settings() -> None:
    settings = get_settings()
    missing = [
        name
        for name, value in (
            ("SMTP_HOST", settings.smtp_host),
            ("SMTP_USERNAME", settings.smtp_username),
            ("SMTP_PASSWORD", settings.smtp_password),
            ("SMTP_FROM_EMAIL", settings.smtp_from_email),
        )
        if not value
    ]
    if missing:
        raise EmailServiceError(
            "Email delivery is not configured. Missing: " + ", ".join(missing)
        )


def _get_candidates(results: Dict[str, Any]) -> List[Dict[str, Any]]:
    candidates = results.get("funding_candidates", []) or []
    return candidates[:MAX_EMAIL_CANDIDATES]


def _build_plain_text_body(candidate_count: int) -> str:
    lines = [
        "ZynthClaw Funding Candidates",
        "",
        "Attached is a PDF report of the latest high-priority open-source projects that may require funding or community support.",
        f"The report currently includes {candidate_count} funding candidate(s).",
        "",
        "Open the attached PDF to see full details for each project.",
        "",
        "Generated by ZynthClaw.",
    ]
    return "\n".join(lines).strip()


def _build_html_body(candidate_count: int) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
        <h2 style="margin-bottom: 8px;">ZynthClaw Funding Candidates</h2>
        <p style="margin-top: 0;">Generated {generated_at}</p>
        <p>
          Attached is a PDF report of the latest open-source projects that appear to be critical
          ecosystem dependencies and may need funding or maintainer support.
        </p>
        <p>
          The report currently includes <strong>{candidate_count}</strong> funding candidate(s).
          Open the attached PDF to see detailed scores and analysis for each project.
        </p>
      </body>
    </html>
    """


def _draw_wrapped_lines(pdf: canvas.Canvas, text: str, x: int, y: int, max_width: int) -> int:
    for paragraph in text.splitlines() or [""]:
        words = paragraph.split()
        if not words:
            y -= 14
            continue

        line = words[0]
        for word in words[1:]:
            candidate_line = f"{line} {word}"
            if pdf.stringWidth(candidate_line, "Helvetica", 10) <= max_width:
                line = candidate_line
                continue

            pdf.drawString(x, y, line)
            y -= 14
            line = word

        pdf.drawString(x, y, line)
        y -= 14

    return y


def _generate_pdf_bytes(candidates: List[Dict[str, Any]]) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    left = 50
    max_width = int(width - 100)
    y = int(height - 50)

    pdf.setTitle("ZynthClaw Funding Candidates")
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(left, y, "ZynthClaw Funding Candidates")
    y -= 24

    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        left,
        y,
        "Generated " + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )
    y -= 24

    for index, candidate in enumerate(candidates, start=1):
        if y < 140:
            pdf.showPage()
            y = int(height - 50)
            pdf.setFont("Helvetica", 10)

        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(left, y, f"{index}. {candidate.get('full_name', 'unknown')}")
        y -= 16

        pdf.setFont("Helvetica", 10)
        stat_lines = [
            f"Risk Level: {candidate.get('risk_flag', 'UNKNOWN')}",
            f"Dependents: {candidate.get('dependents_count', 0):,}",
            f"Impact Score: {candidate.get('impact_score', 0)}",
            f"Maintainer Sustainability Score: {candidate.get('maintainer_sustainability_score', 0)}",
            f"Ecosystem Dependency Score: {candidate.get('ecosystem_dependency_score', 0)}",
            f"Criticality Score: {candidate.get('criticality_score', 0)}",
            f"Open Issues: {candidate.get('open_issues', 0):,}",
            f"Total Contributors: {candidate.get('total_contributors', 0):,}",
            f"Active Maintainers (90d): {candidate.get('active_contributors_90d', 0)}",
            f"URL: {candidate.get('html_url', '')}",
        ]
        for line in stat_lines:
            pdf.drawString(left, y, line)
            y -= 14

        analysis = candidate.get("analysis", "No additional analysis available.")
        y = _draw_wrapped_lines(pdf, f"Analysis: {analysis}", left, y, max_width)
        y -= 10

    pdf.save()
    buffer.seek(0)
    return buffer.getvalue()


def send_funding_targets_email(recipient_email: str, results: Dict[str, Any]) -> int:
    recipient_email = recipient_email.strip()
    if not is_valid_email(recipient_email):
        raise EmailServiceError("Please provide a valid email address.")

    _require_smtp_settings()
    candidates = _get_candidates(results)
    if not candidates:
        raise EmailServiceError(
            "No funding candidates are available yet. Run /scan, /repo, or /funding_targets first."
        )

    settings = get_settings()
    message = EmailMessage()
    message["Subject"] = "ZynthClaw Funding Candidates Report"
    message["From"] = settings.smtp_from_email
    message["To"] = recipient_email

    candidate_count = len(candidates)
    plain_text = _build_plain_text_body(candidate_count)
    html = _build_html_body(candidate_count)
    message.set_content(plain_text)
    message.add_alternative(html, subtype="html")
    message.add_attachment(
        _generate_pdf_bytes(candidates),
        maintype="application",
        subtype="pdf",
        filename="zynthclaw_funding_candidates.pdf",
    )

    if settings.smtp_use_ssl:
        with smtplib.SMTP_SSL(settings.smtp_host, settings.smtp_port, timeout=30) as server:
            server.login(settings.smtp_username, settings.smtp_password)
            server.send_message(message)
    else:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=30) as server:
            server.ehlo()
            if settings.smtp_use_tls:
                server.starttls()
                server.ehlo()
            server.login(settings.smtp_username, settings.smtp_password)
            server.send_message(message)

    return len(candidates)


def _build_plain_text_raw_evaluation(project_handle: str, created_at: str) -> str:
    lines = [
        "ZynthClaw Public Goods Evaluation – Raw Data",
        "",
        f"Project: @{project_handle}",
        f"Generated: {created_at}",
        "",
        "Attached is a PDF containing the raw collated data used to build the impact evaluation:",
        "- Community sentiment and X-related signals (placeholder until X integration is wired).",
        "- Your detailed feedback from Telegram.",
        "- Optional GitHub developer-activity summary if a repo was provided.",
        "",
        "Open the PDF to review and re-interpret the signals in your own workflow.",
    ]
    return "\n".join(lines).strip()


def _build_html_raw_evaluation(project_handle: str, created_at: str) -> str:
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5;">
        <h2 style="margin-bottom: 8px;">ZynthClaw Public Goods Evaluation – Raw Data</h2>
        <p style="margin-top: 0;">Project: @{project_handle}</p>
        <p style="margin-top: 0;">Generated: {created_at}</p>
        <p>
          Attached is a PDF containing the raw collated data used to build the impact evaluation:
        </p>
        <ul>
          <li>Community sentiment and X-related signals (placeholder until X integration is wired).</li>
          <li>Your detailed feedback from Telegram.</li>
          <li>Optional GitHub developer-activity summary if a repo was provided.</li>
        </ul>
        <p>
          Open the PDF to review and re-interpret the signals in your own workflow.
        </p>
      </body>
    </html>
    """


def _generate_raw_evaluation_pdf(evaluation: Dict[str, Any]) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    left = 50
    max_width = int(width - 100)
    y = int(height - 50)

    def draw_block(title: str, text: str) -> None:
        nonlocal y
        if y < 140:
            pdf.showPage()
            y = int(height - 50)
            pdf.setFont("Helvetica", 10)

        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(left, y, title)
        y -= 18
        pdf.setFont("Helvetica", 10)
        nonlocal_max = max_width
        y_local = _draw_wrapped_lines(pdf, text or "N/A", left, y, nonlocal_max)
        y = y_local - 12

    pdf.setTitle("ZynthClaw Public Goods Evaluation – Raw Data")
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(left, y, "ZynthClaw Public Goods Evaluation – Raw Data")
    y -= 24

    pdf.setFont("Helvetica", 10)
    header = (
        f"Project: @{evaluation.get('x_handle', 'unknown')}  |  "
        f"Generated: {evaluation.get('created_at', '')}"
    )
    pdf.drawString(left, y, header)
    y -= 24

    draw_block("Community sentiment summary", evaluation.get("community_sentiment_summary", ""))
    draw_block("User feedback (Telegram)", evaluation.get("user_feedback", ""))

    if evaluation.get("github_repo_url"):
        gh_text = (
            f"Repository: {evaluation.get('github_repo_url')}\n\n"
            f"{evaluation.get('github_summary', '')}"
        )
        draw_block("GitHub developer activity", gh_text)

    draw_block(
        "Impact classification and mechanism design",
        (
            f"Impact classification: {evaluation.get('impact_classification', 'N/A')}\n\n"
            f"{evaluation.get('mechanism_design_recommendation', '')}"
        ),
    )

    pdf.save()
    buffer.seek(0)
    return buffer.getvalue()


def send_raw_evaluation_email(recipient_email: str, evaluation: Dict[str, Any]) -> None:
    recipient_email = recipient_email.strip()
    if not is_valid_email(recipient_email):
        raise EmailServiceError("Please provide a valid email address.")

    _require_smtp_settings()

    handle = evaluation.get("x_handle", "unknown")
    created_at = evaluation.get("created_at", datetime.now(timezone.utc).isoformat())

    settings = get_settings()
    message = EmailMessage()
    message["Subject"] = "ZynthClaw Public Goods Evaluation – Raw Data"
    message["From"] = settings.smtp_from_email
    message["To"] = recipient_email

    plain_text = _build_plain_text_raw_evaluation(handle, created_at)
    html = _build_html_raw_evaluation(handle, created_at)
    message.set_content(plain_text)
    message.add_alternative(html, subtype="html")
    message.add_attachment(
        _generate_raw_evaluation_pdf(evaluation),
        maintype="application",
        subtype="pdf",
        filename="zynthclaw_public_goods_raw_evaluation.pdf",
    )

    if settings.smtp_use_ssl:
        with smtplib.SMTP_SSL(settings.smtp_host, settings.smtp_port, timeout=30) as server:
            server.login(settings.smtp_username, settings.smtp_password)
            server.send_message(message)
    else:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=30) as server:
            server.ehlo()
            if settings.smtp_use_tls:
                server.starttls()
                server.ehlo()
            server.login(settings.smtp_username, settings.smtp_password)
            server.send_message(message)

